name:                lookml
version:             0.1.0.0
github:              "fzakaria/lookml"
license:             BSD3
author:              "Farid Zakaria"
maintainer:          "farid.m.zakaria@gmail.com"
copyright:           "2021 Farid Zakaria"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            A compiler for the LookML language
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fzakaria/lookml#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pretty
- megaparsec
- containers

library:
  source-dirs: src

executables:
  lookml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lookml

tests:
  lookml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lookml
